### PR TITLE
docs(NixOS): Include additional required settings

### PR DESCRIPTION
**Pull request by l0b0**
And more - see commit messages.

### CODE REVIEW

**Comment by nichwall** [comment]
Thanks for updating the config! I don't use nix, so is the port defined somewhere else or is it now just using 13378 or 8234?

**Comment by l0b0** [comment]
> Thanks for updating the config! I don't use nix, so is the port defined somewhere else or is it now just using 13378 or 8234?

There's a [default port](https://search.nixos.org/options?channel=24.05&show=services.audiobookshelf.port&from=0&size=50&sort=relevance&type=packages&query=services.audiobookshelf.port), so there's no need to configure it manually. Any reverse proxy or other configuration which needs to know the port can just [refer to it](https://github.com/audiobookshelf/audiobookshelf-web/pull/105/files#diff-47ae67d39147f494adb50b4a270acbb87ca9a3af34c6b533129b9d6b18fc4cb2R53) rather than relying on hard-coding it.

**Comment by advplyr** [comment]
I didn't see this PR until after merging [this other PR](https://github.com/audiobookshelf/audiobookshelf-web/pull/112/files) adding `proxyWebsockets`.
I also don't use nix so we're just relying on contributors for these.

Is that line needed for the websocket connection?

**Comment by l0b0** [comment]
> I didn't see this PR until after merging [this other PR](https://github.com/audiobookshelf/audiobookshelf-web/pull/112/files) adding `proxyWebsockets`. I also don't use nix so we're just relying on contributors for these.

No worries 😀

> Is that line needed for the websocket connection?

I think so, I wasn't able to play content otherwise.

**Comment by advplyr** [comment]
Thanks!

**Pull request merged**
